import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:meditime/features/history/domain/entities/dose_log.dart';

class ReportService {
  static Future<void> generateHistoryReport({
    required String userName,
    required List<DoseLog> events,
    required Map<String, String> medicineNames, // id -> name
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('MediTime Medication History Report',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                pw.Text(DateTime.now().toIso8601String().split('T').first),
              ],
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Text('Patient Name: $userName', style: const pw.TextStyle(fontSize: 14)),
          pw.SizedBox(height: 20),
          pw.TableHelper.fromTextArray(
            headers: ['Date/Time', 'Medicine', 'Status'],
            data: events.map((e) {
              return [
                e.dateTime.toIso8601String().replaceFirst('T', ' ').split('.').first,
                medicineNames[e.medicineId] ?? 'Unknown',
                e.status.name.toUpperCase(),
              ];
            }).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellHeight: 30,
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerLeft,
              2: pw.Alignment.center,
            },
          ),
          pw.SizedBox(height: 30),
          pw.Footer(
            title: pw.Text('Generated by MediTime App', style: const pw.TextStyle(color: PdfColors.grey)),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'MediTime_Report_${userName}_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  static Future<void> generateEmergencyCardPdf({
    required String name,
    required String bloodType,
    required String allergies,
    required String conditions,
    required String emergencyContact,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a5,
        build: (context) => pw.Container(
          padding: const pw.EdgeInsets.all(20),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.red, width: 3),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Text('EMERGENCY MEDICAL CARD',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16, color: PdfColors.red)),
              ),
              pw.Divider(color: PdfColors.red),
              pw.SizedBox(height: 10),
              pw.Text('NAME: $name', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text('BLOOD TYPE: $bloodType',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.red)),
              pw.SizedBox(height: 15),
              pw.Text('ALLERGIES:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(allergies),
              pw.SizedBox(height: 10),
              pw.Text('CONDITIONS:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(conditions),
              pw.SizedBox(height: 15),
              pw.Text('EMERGENCY CONTACT:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(emergencyContact),
              pw.Spacer(),
              pw.Center(
                child: pw.Text('Powered by MediTime', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              ),
            ],
          ),
        ),
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Emergency_Card_$name.pdf',
    );
  }
}
